- name: download direnv
  get_url:
    url: https://github.com/direnv/direnv/releases/download/v2.30.3/direnv.linux-amd64
    dest: "{{ ansible_env.HOME }}/.local/bin/direnv"
    mode: 0744

- name: add direnv to session init
  blockinfile:
    marker: "# {mark} ANSIBLE DIRENV"
    path: "{{ managed_bashrc_file }}"
    block: |
      eval "$(direnv hook bash)"
