- name: install core system packages
  become: true
  package:
    name: ["cmake"]
  tags:
    - install
    - core

- name: install lesser system packages
  become: true
  package:
    name: [
        "curl",
        "flatpak",
        "lsof",
        "tmux",
        "xclip",
        "tldr",
        "ripgrep",
        "colordiff",
        "tldr",
        "pavucontrol",
      ]
  tags:
    - install

