- name: Ensure .ssh directory exists.
  file:
    path: "{{ dest_key | dirname }}"
    state: directory
    mode: "0700"
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

# - name: Set authorized key took from file
#   authorized_key:
#     user: "eran-local"
#     state: present
#     key: "{{ansible_env.HOME}}/.ssh/id_ed25519.pub"
#   with_fileglob:
#   - "{{ansible_env.HOME}}/.ssh/*.pub"
