- name: install zsh
  become: true
  package:
    name: zsh
    state: present
  tags:
    - zsh

- name: change shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags:
    - zsh

- name: remove .zsh-ansible file if it exists
  file:
    path: "{{ansible_env.HOME}}/.zsh-ansible"
    state: absent
  tags:
    - zsh

- name: ensure .zsh-ansible file exists
  file:
    path: "{{ansible_env.HOME}}/.zsh-ansible"
    state: touch
  tags:
    - zsh