- name: clone fzf repository
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: '{{ansible_env.HOME}}/.fzf'
    depth: 1
  tags:
    - fzf

- name: run fzf install script
  command:
    cmd: '{{ansible_env.HOME}}/.fzf/install'
    creates: '{{ansible_env.HOME}}/.fzf/bin/fzf'
  tags:
    - fzf

- name: ensure fzf is initialized in zsh-ansible
  lineinfile:
    path: "{{ansible_env.HOME}}/.zsh-ansible"
    line: '[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh'
    state: present
    insertafter: EOF
    create: yes
  tags:
    - fzf
