- name: install starship
  ansible.builtin.shell:
    cmd: curl -sS https://starship.rs/install.sh | sh -s -- --yes
  tags:
    - starship
    - zsh

- name: ensure starship is initialized in zsh-ansible
  lineinfile:
    path: "{{ansible_env.HOME}}/.zsh-ansible"
    line: 'eval "$(starship init zsh)"'
    state: present
    insertafter: EOF
    create: yes
  become: no
  tags:
    - starship
    - zsh